--- #YAML:1.0
name:               MobaSiF-Template
version:            0.02
abstract:           Very fast Template module written by XS.
author:
    - bobpp < bobpp@cpan.org >
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
